// Code generated by goyacc -o adm.go adm.y. DO NOT EDIT.

//line adm.y:2
package parser

import __yyfmt__ "fmt"

//line adm.y:2

import "fmt"

//line adm.y:13
type yySymType struct {
	yys  int
	line LogLine

	stringValue string
	floatValue  float64

	player   Player
	position Position
}

const STRING = 57346
const FLOAT = 57347
const TIMESTAMP = 57348
const ID = 57349
const TOK_PIPE = 57350
const TOK_LEFT_ARROW = 57351
const TOK_RIGHT_ARROW = 57352
const TOK_EQUALS = 57353
const TOK_COMMA = 57354
const TOK_LEFT_PAREN = 57355
const TOK_RIGHT_PAREN = 57356
const TOK_PLAYER = 57357
const TOK_ID = 57358
const TOK_IS = 57359
const TOK_POS = 57360
const TOK_CONNECTING = 57361
const TOK_CONNECTED = 57362

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"FLOAT",
	"TIMESTAMP",
	"ID",
	"TOK_PIPE",
	"TOK_LEFT_ARROW",
	"TOK_RIGHT_ARROW",
	"TOK_EQUALS",
	"TOK_COMMA",
	"TOK_LEFT_PAREN",
	"TOK_RIGHT_PAREN",
	"TOK_PLAYER",
	"TOK_ID",
	"TOK_IS",
	"TOK_POS",
	"TOK_CONNECTING",
	"TOK_CONNECTED",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line adm.y:94

// 15:34:20 | Player "jmhobbs" (id=BFDIjY8X3a21fFxgXW339fE0IsxOK0kI7xlfig3HN1I= pos=<17491.9, 6849.4, 16.1>) is connected

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 24

var yyAct = [...]int8{
	10, 11, 14, 8, 7, 17, 16, 12, 22, 20,
	24, 18, 5, 13, 4, 23, 21, 19, 9, 1,
	3, 2, 15, 6,
}

var yyPact = [...]int16{
	8, -1000, -1000, -1000, 4, -11, -14, 14, -19, -6,
	-1000, -1000, 6, -12, -1000, -9, 2, -1000, 12, -3,
	11, -4, 10, 0, -1000,
}

var yyPgo = [...]int8{
	0, 23, 22, 21, 20, 19,
}

var yyR1 = [...]int8{
	0, 5, 5, 3, 4, 1, 1, 2,
}

var yyR2 = [...]int8{
	0, 1, 1, 5, 5, 5, 6, 8,
}

var yyChk = [...]int16{
	-1000, -5, -3, -4, 6, 8, -1, 15, 17, 4,
	19, 20, 13, 7, 14, -2, 18, 14, 9, 5,
	12, 5, 12, 5, 10,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 0, 0, 0, 0, 0, 0,
	3, 4, 0, 0, 5, 0, 0, 6, 0, 0,
	0, 0, 0, 0, 7,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line adm.y:34
		{
			line = yyDollar[1].line
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line adm.y:37
		{
			line = yyDollar[1].line
		}
	case 3:
		yyDollar = yyS[yypt-5 : yypt+1]
//line adm.y:43
		{
			yyVAL.line = LogLine{
				Timestamp: yyDollar[1].stringValue,
				Type:      "CONNECTING",
				Player:    &yyDollar[3].player,
			}
		}
	case 4:
		yyDollar = yyS[yypt-5 : yypt+1]
//line adm.y:53
		{
			yyVAL.line = LogLine{
				Timestamp: yyDollar[1].stringValue,
				Type:      "CONNECTED",
				Player:    &yyDollar[3].player,
			}
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line adm.y:63
		{
			fmt.Printf("!! player: %s\n", yyDollar[2].stringValue)
			fmt.Printf("!!     id: %s\n", yyDollar[4].stringValue)
			yyVAL.player = Player{
				Name: yyDollar[2].stringValue,
				ID:   yyDollar[4].stringValue,
			}
		}
	case 6:
		yyDollar = yyS[yypt-6 : yypt+1]
//line adm.y:71
		{
			fmt.Printf("!! player: %s\n", yyDollar[2].stringValue)
			fmt.Printf("!!     id: %s\n", yyDollar[4].stringValue)
			fmt.Printf("!!     pos: <%f, %f, %f>\n", yyDollar[5].position.X, yyDollar[5].position.Y, yyDollar[5].position.Z)
			yyVAL.player = Player{
				Name:     yyDollar[2].stringValue,
				ID:       yyDollar[4].stringValue,
				Position: &yyDollar[5].position,
			}
		}
	case 7:
		yyDollar = yyS[yypt-8 : yypt+1]
//line adm.y:84
		{
			fmt.Printf("!!     position: <%f, %f, %f>\n", yyDollar[3].floatValue, yyDollar[5].floatValue, yyDollar[7].floatValue)
			yyVAL.position = Position{
				X: yyDollar[3].floatValue,
				Y: yyDollar[5].floatValue,
				Z: yyDollar[7].floatValue,
			}
		}
	}
	goto yystack /* stack new state and value */
}
